/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedMigracaoGruposRouteImport } from './routes/_authenticated/migracao-grupos'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedFerramentasRouteImport } from './routes/_authenticated/ferramentas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConexoesRouteImport } from './routes/_authenticated/conexoes'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBroadcastsRouteImport } from './routes/_authenticated/broadcasts'
import { Route as AuthenticatedAgendamentosRouteImport } from './routes/_authenticated/agendamentos'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiGoogleAuthorizeRouteImport } from './routes/api/google/authorize'
import { Route as ApiPublicWaTickRouteImport } from './routes/api/public/wa/tick'
import { Route as ApiPublicWaDebugRouteImport } from './routes/api/public/wa/debug'
import { Route as ApiPublicWaWebhookInstanceRouteImport } from './routes/api/public/wa/webhook.$instance'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMigracaoGruposRoute =
  AuthenticatedMigracaoGruposRouteImport.update({
    id: '/migracao-grupos',
    path: '/migracao-grupos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFerramentasRoute =
  AuthenticatedFerramentasRouteImport.update({
    id: '/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConexoesRoute = AuthenticatedConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBroadcastsRoute = AuthenticatedBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendamentosRoute =
  AuthenticatedAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAuthorizeRoute = ApiGoogleAuthorizeRouteImport.update({
  id: '/api/google/authorize',
  path: '/api/google/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaTickRoute = ApiPublicWaTickRouteImport.update({
  id: '/api/public/wa/tick',
  path: '/api/public/wa/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaDebugRoute = ApiPublicWaDebugRouteImport.update({
  id: '/api/public/wa/debug',
  path: '/api/public/wa/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaWebhookInstanceRoute =
  ApiPublicWaWebhookInstanceRouteImport.update({
    id: '/api/public/wa/webhook/$instance',
    path: '/api/public/wa/webhook/$instance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/migracao-grupos': typeof AuthenticatedMigracaoGruposRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/google/authorize': typeof ApiGoogleAuthorizeRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/public/wa/debug': typeof ApiPublicWaDebugRoute
  '/api/public/wa/tick': typeof ApiPublicWaTickRoute
  '/api/public/wa/webhook/$instance': typeof ApiPublicWaWebhookInstanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/migracao-grupos': typeof AuthenticatedMigracaoGruposRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/google/authorize': typeof ApiGoogleAuthorizeRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/public/wa/debug': typeof ApiPublicWaDebugRoute
  '/api/public/wa/tick': typeof ApiPublicWaTickRoute
  '/api/public/wa/webhook/$instance': typeof ApiPublicWaWebhookInstanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/_authenticated/broadcasts': typeof AuthenticatedBroadcastsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/conexoes': typeof AuthenticatedConexoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ferramentas': typeof AuthenticatedFerramentasRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/migracao-grupos': typeof AuthenticatedMigracaoGruposRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/google/authorize': typeof ApiGoogleAuthorizeRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/public/wa/debug': typeof ApiPublicWaDebugRoute
  '/api/public/wa/tick': typeof ApiPublicWaTickRoute
  '/api/public/wa/webhook/$instance': typeof ApiPublicWaWebhookInstanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/agendamentos'
    | '/broadcasts'
    | '/chat'
    | '/conexoes'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/ferramentas'
    | '/logs'
    | '/migracao-grupos'
    | '/usuarios'
    | '/api/google/authorize'
    | '/api/google/callback'
    | '/api/public/wa/debug'
    | '/api/public/wa/tick'
    | '/api/public/wa/webhook/$instance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/agendamentos'
    | '/broadcasts'
    | '/chat'
    | '/conexoes'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/ferramentas'
    | '/logs'
    | '/migracao-grupos'
    | '/usuarios'
    | '/api/google/authorize'
    | '/api/google/callback'
    | '/api/public/wa/debug'
    | '/api/public/wa/tick'
    | '/api/public/wa/webhook/$instance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/agendamentos'
    | '/_authenticated/broadcasts'
    | '/_authenticated/chat'
    | '/_authenticated/conexoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contatos'
    | '/_authenticated/dashboard'
    | '/_authenticated/ferramentas'
    | '/_authenticated/logs'
    | '/_authenticated/migracao-grupos'
    | '/_authenticated/usuarios'
    | '/api/google/authorize'
    | '/api/google/callback'
    | '/api/public/wa/debug'
    | '/api/public/wa/tick'
    | '/api/public/wa/webhook/$instance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGoogleAuthorizeRoute: typeof ApiGoogleAuthorizeRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiPublicWaDebugRoute: typeof ApiPublicWaDebugRoute
  ApiPublicWaTickRoute: typeof ApiPublicWaTickRoute
  ApiPublicWaWebhookInstanceRoute: typeof ApiPublicWaWebhookInstanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/migracao-grupos': {
      id: '/_authenticated/migracao-grupos'
      path: '/migracao-grupos'
      fullPath: '/migracao-grupos'
      preLoaderRoute: typeof AuthenticatedMigracaoGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas': {
      id: '/_authenticated/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AuthenticatedFerramentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conexoes': {
      id: '/_authenticated/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof AuthenticatedConexoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broadcasts': {
      id: '/_authenticated/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof AuthenticatedBroadcastsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agendamentos': {
      id: '/_authenticated/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AuthenticatedAgendamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/authorize': {
      id: '/api/google/authorize'
      path: '/api/google/authorize'
      fullPath: '/api/google/authorize'
      preLoaderRoute: typeof ApiGoogleAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/tick': {
      id: '/api/public/wa/tick'
      path: '/api/public/wa/tick'
      fullPath: '/api/public/wa/tick'
      preLoaderRoute: typeof ApiPublicWaTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/debug': {
      id: '/api/public/wa/debug'
      path: '/api/public/wa/debug'
      fullPath: '/api/public/wa/debug'
      preLoaderRoute: typeof ApiPublicWaDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/webhook/$instance': {
      id: '/api/public/wa/webhook/$instance'
      path: '/api/public/wa/webhook/$instance'
      fullPath: '/api/public/wa/webhook/$instance'
      preLoaderRoute: typeof ApiPublicWaWebhookInstanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendamentosRoute: typeof AuthenticatedAgendamentosRoute
  AuthenticatedBroadcastsRoute: typeof AuthenticatedBroadcastsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConexoesRoute: typeof AuthenticatedConexoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFerramentasRoute: typeof AuthenticatedFerramentasRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMigracaoGruposRoute: typeof AuthenticatedMigracaoGruposRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendamentosRoute: AuthenticatedAgendamentosRoute,
  AuthenticatedBroadcastsRoute: AuthenticatedBroadcastsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConexoesRoute: AuthenticatedConexoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFerramentasRoute: AuthenticatedFerramentasRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMigracaoGruposRoute: AuthenticatedMigracaoGruposRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGoogleAuthorizeRoute: ApiGoogleAuthorizeRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiPublicWaDebugRoute: ApiPublicWaDebugRoute,
  ApiPublicWaTickRoute: ApiPublicWaTickRoute,
  ApiPublicWaWebhookInstanceRoute: ApiPublicWaWebhookInstanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
